name: Verify runs-on ubuntu-22.04 vs ubuntu-20.04

on:
  workflow_dispatch:

jobs:
  ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - name: setup myuser
        shell: bash
        run: |
          echo 'set -x; mkdir subdir1 $(pwd)/subdir2' >build.sh
          chmod +x build.sh
          sudo groupadd -g 501 myuser
          sudo useradd -u 501 -g myuser myuser
          sudo chown -R myuser:myuser .
          ls -ld ~/

      - name: test that sudo mkdir works
        shell: bash
        run: |
          sudo -u myuser ./build.sh
          ls -l

  ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:
      - name: setup myuser
        shell: bash
        run: |
          echo 'set -x; mkdir subdir1 $(pwd)/subdir2' >build.sh
          chmod +x build.sh
          sudo groupadd -g 501 myuser
          sudo useradd -u 501 -g myuser myuser
          sudo chown -R myuser:myuser .
          ls -ld ~/
          echo Making directory accessible
          sudo chmod o+x . .. ../.. ../../..

      - name: test that sudo mkdir works
        shell: bash
        run: |
          sudo -u myuser ./build.sh
          ls -l
